package com.example.demo01.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.id
     *
     * @mbg.generated Wed Jan 01 16:03:28 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.account_id
     *
     * @mbg.generated Wed Jan 01 16:03:28 CST 2020
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.name
     *
     * @mbg.generated Wed Jan 01 16:03:28 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.token
     *
     * @mbg.generated Wed Jan 01 16:03:28 CST 2020
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.gmt_create
     *
     * @mbg.generated Wed Jan 01 16:03:28 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.gmt_modified
     *
     * @mbg.generated Wed Jan 01 16:03:28 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.avatar_url
     *
     * @mbg.generated Wed Jan 01 16:03:28 CST 2020
     */
    private String avatarUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.id
     *
     * @return the value of users.id
     *
     * @mbg.generated Wed Jan 01 16:03:28 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.id
     *
     * @param id the value for users.id
     *
     * @mbg.generated Wed Jan 01 16:03:28 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.account_id
     *
     * @return the value of users.account_id
     *
     * @mbg.generated Wed Jan 01 16:03:28 CST 2020
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.account_id
     *
     * @param accountId the value for users.account_id
     *
     * @mbg.generated Wed Jan 01 16:03:28 CST 2020
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.name
     *
     * @return the value of users.name
     *
     * @mbg.generated Wed Jan 01 16:03:28 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.name
     *
     * @param name the value for users.name
     *
     * @mbg.generated Wed Jan 01 16:03:28 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.token
     *
     * @return the value of users.token
     *
     * @mbg.generated Wed Jan 01 16:03:28 CST 2020
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.token
     *
     * @param token the value for users.token
     *
     * @mbg.generated Wed Jan 01 16:03:28 CST 2020
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.gmt_create
     *
     * @return the value of users.gmt_create
     *
     * @mbg.generated Wed Jan 01 16:03:28 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.gmt_create
     *
     * @param gmtCreate the value for users.gmt_create
     *
     * @mbg.generated Wed Jan 01 16:03:28 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.gmt_modified
     *
     * @return the value of users.gmt_modified
     *
     * @mbg.generated Wed Jan 01 16:03:28 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.gmt_modified
     *
     * @param gmtModified the value for users.gmt_modified
     *
     * @mbg.generated Wed Jan 01 16:03:28 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.avatar_url
     *
     * @return the value of users.avatar_url
     *
     * @mbg.generated Wed Jan 01 16:03:28 CST 2020
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.avatar_url
     *
     * @param avatarUrl the value for users.avatar_url
     *
     * @mbg.generated Wed Jan 01 16:03:28 CST 2020
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }
}